blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')),
    path('', include('comments.urls', namespace="comments")),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comments/urls.py
from django.urls import path
from comments.views import add_comment

app_name="comments"

urlpatterns = [
    path('comment/<int:article_id>', add_comment, name="add_comment")
]

main/urls.py
from django.urls import path

from main.views import article_view
from main.views import main_view
from main.views import add_article

app_name = "main"
urlpatterns = [

    path('article/<int:art_id>/', article_view, name="single_art"),
    path('', main_view, name="home"),
    path('add-article/', add_article, name="add-article"),
]

comments/models.py
from django.db import models
from django.contrib.auth.models import User

class Comment(models.Model):

    content = models.TextField(
        verbose_name='Comment content'
    )
    article = models.ForeignKey(
        'main.Article',
        on_delete=models.CASCADE,
        verbose_name='Article'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return '{}...'.format(self.content[:10])

main/models.py
from django.db import models
from django.contrib.auth.models import User
from tags.models import Tag
from django.urls import reverse

class Article(models.Model):

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Created'
    )
    image = models.ImageField(
        upload_to='articles_images',
        verbose_name="image"
    )
    title = models.CharField(
        max_length=255,
        verbose_name='Title'
    )
    content = models.TextField(
        verbose_name='Content'
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name='Tags',
        help_text='Tags for dividing articles to categories',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Author",
    )

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("main:single_art", args=[self.id])

tags/models.py
from django.db import models


class Tag(models.Model):

    name = models.CharField(
        max_length=255,
    )

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name

comments/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound
from django.shortcuts import redirect
from comments.models import Comment
from django.urls import reverse
# Create your views here.

def add_comment(request, article_id):
    if request.user.is_authenticated and request.POST:
        print(request.POST)
        comment = Comment()
        comment.author= request.user
        comment.article_id = article_id
        comment.content = request.POST["comment_body"]
        comment.save()
        return redirect(
            reverse("main:single_art", args=[article_id])
        )
    else:
        return HttpResponseNotFound()

main/views.py
from django.shortcuts import render

from main.models import Article
from comments.models import Comment

from django.http import HttpResponseNotFound
from django.shortcuts import redirect
from django.urls import reverse


def article_view(request, art_id):
    article = Article.objects.get(id=art_id)
    comment = Comment.objects.filter(article_id = art_id)
    print(comment)
    context = {
        'article': article,
        'comment': comment
    }
    return render(request, 'main/single_article.html', context)
def main_view(request):
    articles = Article.objects.all()[:10]
    context = {
        "articles": articles,
    }
    return render(request, 'main/home.html', context)

def add_article(request):
    if request.user.is_authenticated and request.POST:
        print(request.POST)
        article = Article()
        article.author= request.user
        article.title = request.POST["article_title"]
        article.content = request.POST["article_body"]
        article.save()
        return redirect(request.META['HTTP_REFERER'])
    else:
        return render(request, 'main/add-article.html')

tags/views.py
from django.shortcuts import render

# Create your views here.

comments/templates/form.html
<form action="{% url 'comments:add_comment' article_id=article_id %}" method="post">
   {% csrf_token %}
    <textarea name="comment_body" id="" cols="90" rows="6"></textarea>
    <br>
    <button type="submit">Add comment</button>
</form>

main/templates/main/add-article.html
{% extends "base.html" %}

{% block main_colomn %}
<form action="" method="post">
  {% csrf_token %}
  <h4>Title</h4>
  <input type="text" name="article_title">
  <h4>Content</h4>
  <textarea name="article_body" cols="90" rows="3"></textarea>
  <br>
  <button type="submit">Add article</button>
</form>

{% endblock main_colomn %}

main/templates/main/home.html
{% extends "base.html" %}

{% block main_colomn %} 

   <div class="row">
    {% for article in articles %}
       
        <div class="col-md-3">
            <h3>{{article.title}}</h3>
            <p>{{article.content|truncatechars:"50"}}</p>
            <a href="{{article.get_absolute_url}}">Read more</a>
        </div>
        
    {% endfor %} 
    </div>
{% endblock main_colomn %}

main/templates/main/single_article.html
{% extends "base.html" %} {% block title %} {{ article.title }} {% endblock title %} {% block main_colomn %}
<!-- Title -->
<h1 class="mt-4">{{ article.title }}</h1>

<!-- Author -->
<p class="lead">
    by
    <a href="#">{{article.author.username}}</a>
</p>

<hr>

<!-- Date/Time -->
<p>{{ article.created }}</p>

<hr>

<hr>

<!-- Post Content -->
<p class="lead">
    {{ article.content }}
</p>

<a href="{% url 'main:home' %}">Back to home</a>
<hr>

<!-- Comments Form -->
<div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
       {% include "form.html" with article_id=article.id %}
    </div>
</div>

<!-- Single Comment -->
{% for comment in comment %}
<div class="media mb-4">
    <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
    <div class="media-body">
        <h5 class="mt-0">{{comment.author}}</h5>
        {{comment.content}}
    </div>
</div>
{% endfor %}



{% endblock main_colomn %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Logos blog{% endblock %}</title>

    <link href="{% static "vendor/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

    <link href="{% static "css/blog-post.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container base-cont ">
      <div class="row">

        <!-- Post Content Column -->
        <div class="col-lg-8">
          {% block main_colomn %}
            
          {% endblock main_colomn %}
        </div>
        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">
          {% block sidebar %}
          <h3>Latest Articles</h3>
          {% for article in latest_articles%}
           <div>
            <a href="{{article.get_absolute_url}}">{{article.title}}</a>
            <p>{{artiles.content}}</p>
            </div>
            {% endfor %}
            <h3>Comments</h3>
          {% for comment in articles_comments%}
           <div>
            <a href="{{comment.article.get_absolute_url}}">{{comment.content}}</a>
            </div>
            {% endfor %}
          {% endblock sidebar %}
        </div>

      </div>
    </div>

    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
    </footer>

    <script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
    <script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>

</html>